import React from 'react';
import { Icon } from './BaseIcon';

export function ClockIcon() {
  return (
    <Icon>
      <rect x="13" y="5" width="1" height="1"></rect>
      <rect x="14" y="5" width="1" height="1"></rect>
      <rect x="15" y="5" width="1" height="1"></rect>
      <rect x="16" y="5" width="1" height="1"></rect>
      <rect x="17" y="5" width="1" height="1"></rect>
      <rect x="18" y="5" width="1" height="1"></rect>
      <rect x="11" y="6" width="1" height="1"></rect>
      <rect x="12" y="6" width="1" height="1"></rect>
      <rect x="13" y="6" width="1" height="1"></rect>
      <rect x="14" y="6" width="1" height="1"></rect>
      <rect x="15" y="6" width="1" height="1"></rect>
      <rect x="16" y="6" width="1" height="1"></rect>
      <rect x="17" y="6" width="1" height="1"></rect>
      <rect x="18" y="6" width="1" height="1"></rect>
      <rect x="19" y="6" width="1" height="1"></rect>
      <rect x="20" y="6" width="1" height="1"></rect>
      <rect x="10" y="7" width="1" height="1"></rect>
      <rect x="11" y="7" width="1" height="1"></rect>
      <rect x="12" y="7" width="1" height="1"></rect>
      <rect x="19" y="7" width="1" height="1"></rect>
      <rect x="20" y="7" width="1" height="1"></rect>
      <rect x="21" y="7" width="1" height="1"></rect>
      <rect x="9" y="8" width="1" height="1"></rect>
      <rect x="10" y="8" width="1" height="1"></rect>
      <rect x="21" y="8" width="1" height="1"></rect>
      <rect x="22" y="8" width="1" height="1"></rect>
      <rect x="8" y="9" width="1" height="1"></rect>
      <rect x="9" y="9" width="1" height="1"></rect>
      <rect x="16" y="9" width="1" height="1"></rect>
      <rect x="17" y="9" width="1" height="1"></rect>
      <rect x="22" y="9" width="1" height="1"></rect>
      <rect x="23" y="9" width="1" height="1"></rect>
      <rect x="7" y="10" width="1" height="1"></rect>
      <rect x="8" y="10" width="1" height="1"></rect>
      <rect x="16" y="10" width="1" height="1"></rect>
      <rect x="17" y="10" width="1" height="1"></rect>
      <rect x="23" y="10" width="1" height="1"></rect>
      <rect x="24" y="10" width="1" height="1"></rect>
      <rect x="6" y="11" width="1" height="1"></rect>
      <rect x="7" y="11" width="1" height="1"></rect>
      <rect x="16" y="11" width="1" height="1"></rect>
      <rect x="17" y="11" width="1" height="1"></rect>
      <rect x="24" y="11" width="1" height="1"></rect>
      <rect x="25" y="11" width="1" height="1"></rect>
      <rect x="6" y="12" width="1" height="1"></rect>
      <rect x="7" y="12" width="1" height="1"></rect>
      <rect x="16" y="12" width="1" height="1"></rect>
      <rect x="17" y="12" width="1" height="1"></rect>
      <rect x="24" y="12" width="1" height="1"></rect>
      <rect x="25" y="12" width="1" height="1"></rect>
      <rect x="5" y="13" width="1" height="1"></rect>
      <rect x="6" y="13" width="1" height="1"></rect>
      <rect x="16" y="13" width="1" height="1"></rect>
      <rect x="17" y="13" width="1" height="1"></rect>
      <rect x="25" y="13" width="1" height="1"></rect>
      <rect x="26" y="13" width="1" height="1"></rect>
      <rect x="5" y="14" width="1" height="1"></rect>
      <rect x="6" y="14" width="1" height="1"></rect>
      <rect x="16" y="14" width="1" height="1"></rect>
      <rect x="17" y="14" width="1" height="1"></rect>
      <rect x="25" y="14" width="1" height="1"></rect>
      <rect x="26" y="14" width="1" height="1"></rect>
      <rect x="5" y="15" width="1" height="1"></rect>
      <rect x="6" y="15" width="1" height="1"></rect>
      <rect x="16" y="15" width="1" height="1"></rect>
      <rect x="17" y="15" width="1" height="1"></rect>
      <rect x="25" y="15" width="1" height="1"></rect>
      <rect x="26" y="15" width="1" height="1"></rect>
      <rect x="5" y="16" width="1" height="1"></rect>
      <rect x="6" y="16" width="1" height="1"></rect>
      <rect x="16" y="16" width="1" height="1"></rect>
      <rect x="17" y="16" width="1" height="1"></rect>
      <rect x="25" y="16" width="1" height="1"></rect>
      <rect x="26" y="16" width="1" height="1"></rect>
      <rect x="5" y="17" width="1" height="1"></rect>
      <rect x="6" y="17" width="1" height="1"></rect>
      <rect x="15" y="17" width="1" height="1"></rect>
      <rect x="16" y="17" width="1" height="1"></rect>
      <rect x="25" y="17" width="1" height="1"></rect>
      <rect x="26" y="17" width="1" height="1"></rect>
      <rect x="5" y="18" width="1" height="1"></rect>
      <rect x="6" y="18" width="1" height="1"></rect>
      <rect x="14" y="18" width="1" height="1"></rect>
      <rect x="15" y="18" width="1" height="1"></rect>
      <rect x="25" y="18" width="1" height="1"></rect>
      <rect x="26" y="18" width="1" height="1"></rect>
      <rect x="6" y="19" width="1" height="1"></rect>
      <rect x="7" y="19" width="1" height="1"></rect>
      <rect x="13" y="19" width="1" height="1"></rect>
      <rect x="14" y="19" width="1" height="1"></rect>
      <rect x="24" y="19" width="1" height="1"></rect>
      <rect x="25" y="19" width="1" height="1"></rect>
      <rect x="6" y="20" width="1" height="1"></rect>
      <rect x="7" y="20" width="1" height="1"></rect>
      <rect x="13" y="20" width="1" height="1"></rect>
      <rect x="24" y="20" width="1" height="1"></rect>
      <rect x="25" y="20" width="1" height="1"></rect>
      <rect x="7" y="21" width="1" height="1"></rect>
      <rect x="8" y="21" width="1" height="1"></rect>
      <rect x="23" y="21" width="1" height="1"></rect>
      <rect x="24" y="21" width="1" height="1"></rect>
      <rect x="8" y="22" width="1" height="1"></rect>
      <rect x="9" y="22" width="1" height="1"></rect>
      <rect x="22" y="22" width="1" height="1"></rect>
      <rect x="23" y="22" width="1" height="1"></rect>
      <rect x="9" y="23" width="1" height="1"></rect>
      <rect x="10" y="23" width="1" height="1"></rect>
      <rect x="21" y="23" width="1" height="1"></rect>
      <rect x="22" y="23" width="1" height="1"></rect>
      <rect x="10" y="24" width="1" height="1"></rect>
      <rect x="11" y="24" width="1" height="1"></rect>
      <rect x="12" y="24" width="1" height="1"></rect>
      <rect x="19" y="24" width="1" height="1"></rect>
      <rect x="20" y="24" width="1" height="1"></rect>
      <rect x="21" y="24" width="1" height="1"></rect>
      <rect x="11" y="25" width="1" height="1"></rect>
      <rect x="12" y="25" width="1" height="1"></rect>
      <rect x="13" y="25" width="1" height="1"></rect>
      <rect x="14" y="25" width="1" height="1"></rect>
      <rect x="15" y="25" width="1" height="1"></rect>
      <rect x="16" y="25" width="1" height="1"></rect>
      <rect x="17" y="25" width="1" height="1"></rect>
      <rect x="18" y="25" width="1" height="1"></rect>
      <rect x="19" y="25" width="1" height="1"></rect>
      <rect x="20" y="25" width="1" height="1"></rect>
      <rect x="13" y="26" width="1" height="1"></rect>
      <rect x="14" y="26" width="1" height="1"></rect>
      <rect x="15" y="26" width="1" height="1"></rect>
      <rect x="16" y="26" width="1" height="1"></rect>
      <rect x="17" y="26" width="1" height="1"></rect>
      <rect x="18" y="26" width="1" height="1"></rect>
    </Icon>
  );
}
